### ISSUE TITLE
Problems running inference on Keras model

### ISSUE THREAD

**Issue by florence27** [PAIR-code/what-if-tool#126]
Hi everyone, 

I am trying to use my Keras model for the WIT in Tensorboard, but unfortunately I am not able to load it correctly. The model I use is a `Sequential` model with some `Dense` layers. I am saving it as follows: 

```
builder = tf.compat.v1.saved_model.Builder(export_path)
signature = tf.compat.v1.saved_model.predict_signature_def(
        inputs={'input': model.inputs[0]}, outputs={'output': model.outputs[0]})
with tf.keras.backend.get_session() as sess:    
        builder.add_meta_graph_and_variables(
            sess=sess,
            tags=[tf.compat.v1.saved_model.tag_constants.SERVING],
            signature_def_map={
                tf.compat.v1.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature
            })

        builder.save()
```

I serve it using Docker: 

```
docker run -t --rm -p 8500:8500 \
    -v "/path/to/model:/models/census_model" \
    -e MODEL_NAME=census_model \
    tensorflow/serving &
```

Then I start my Tensorboard, which is working perfectly fine, and open the WIT-Settings, in order to load my model. Since the method name in the model signature is `tensorflow/serving/predict`, I am using the Predict-API and providing the name of input and output. Unfortunately, when trying to apply all the settings, I get the following error message: 

`1055,"grpc_message":"Expects arg[0] to be float but string is provided","grpc_status":3`

I've looked into my `.tfrecord` file, and even looked at the datatypes from the datapoints in the WIT, but I can't find any error in there. Any help here would be really appreciated! 

My setup is: 

- OS system: macOS Catalina, 10.15.6
- Tensorflow-version: 1.15.0
- Python-version: 3.6.12

Thanks & Cheers!

**Comment by jameswex** [comment]
Thanks for reaching out. I haven't tried using WIT with a TF-serving model that was exported from a keras model (I've used it with TF Estimators), so I'm not sure of the problem off the top of my head. Are you able to provide your saved model and tfrecord file for me to repro the problem with?

**Comment by florence27** [comment]
Sure, here you go. Thanks a lot for having a look at it! 
[model_files.zip](https://github.com/PAIR-code/what-if-tool/files/5259595/model_files.zip)

**Comment by jameswex** [comment]
Thanks! The issue seems to be that the WIT / TF Serving integration was done when the estimator API was recommended, before the new Keras API. The estimator API could output model signatures where the input to the model is a serialized tf.Example protocol buffer containing all the features. This is what the WIT use-case with TF Serving expects. Your model takes as input a tensor of 11 floats directly (not a tf.Example containing 11 features that each contain floats). And what WIT does is it serializes the Example proto for each example and sends them to the served model, assuming this is what the model expects as its one input feature.

In order to use WIT with your model as it is defined today, you will have to use it with a custom prediction function (which you can do using WIT in TensorBoard, or using it inside of notebooks), where you write a python function that takes in a list of examples to infer (in the format from your tf record file), calls the model (either directly in memory, or it could call to TF serving from python with the examples in the format that the served model expects), and returns the results.

Both the WIT TensorBoard (https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/) and notebook (https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/) tutorials mention how to set up with custom predict functions and include links to some example functions.

Let me know if you need any help with this.

**Comment by florence27** [comment]
Thank you so much for your detailed answer @jameswex ! 

Actually, I need your help with the setup of the `custom_predict_fn()`. As I understood from [here](https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/), my `custom_predict_fn()` may lie in any python file, as long as I specify the path to this file via `--whatif-use-unsafe-custom-prediction [file path]`. Nevertheless, when I run the `tensorboard` command with the `--whatif-use-unsafe-custom-prediction` specified as my training script, where I build & train the Keras model, I get a `Failed to load the custom predict function.` error. 

So, I assume now that I have to write a `foo.py` file, which only contains the `custom_predict_fn()`, am I right here?

**Comment by jameswex** [comment]
Yes, one example foo.py file can be seen in the WIT readme at https://github.com/PAIR-code/what-if-tool#can-i-use-a-custom-prediction-function-in-tensorboard

Let me know if that helps.

**Comment by florence27** [comment]
Thanks, that helped me a lot already. 

However, I'm still having troubles to setup the `custom_predict_fn()` correctly. Is there any neat way to unpack the tfrecord-file in such a way that I can use it as input for my Keras model? I tried using `tf.io.parse_single_example()`, but every time I'm running my `foo.py` with this function-call inside of my `custom_predict_fn()`, I get the following Tensorboard-Error: 
`Failed to load the custom predict function. Have you defined a function named custom_predict_fn?`

I checked the path to my `foo.py` and it's right, so maybe you could help me here.

**Comment by jameswex** [comment]
Do you get that error on start-up when using the --whatif-use-unsafe-custom-prediction flag to point to that file? If so, are there other errors above that error? It is most likely that the foo.py cannot be interpreted due to some syntax issue in that file. If you try with the example custom predict function linked above (that just returns random predictions) does it work correctly?

I think you'll want to debug your custom predict function code outside the scope of TensorBoard/WIT to first ensure you can get the logic working on its own.

The input to your function will be a list of tf.Example proto objects, so you should be able to just use `examples[0].features.feature['age'].float_list.value[0]` or similar to extract the features from your individual feature values. In that case, a feature named 'age' contains a single float value to extract, which we extract from the first example in the list.

**Comment by florence27** [comment]
It worked, thank you so much for your support! 👍
