### ISSUE TITLE
1.7.1-alpha.3 Breaks JupyterLab terminal

### ISSUE THREAD

**Issue by gogasca** [PAIR-code/what-if-tool#137]
AI Platform Notebooks m59. JupyterLab Version 1.2.16
When opening Terminal I'm getting
```
Launcher error
i is not a constructor
```
https://i.stack.imgur.com/fHlkG.png

**Comment by gogasca** [comment]
StackOverflow reference: https://stackoverflow.com/questions/64778387/ai-platform-notebooks-unable-to-launch-terminal/64778432#64778432

**Comment by jameswex** [comment]
Thanks @gogasca . I did not mean to apply the "latest" tag to 1.7.1.a3. I am testing some updates but as you can see, the new version isn't ready. I have reverted the latest tag to 1.7.0, which is the version that people should be using.

**Comment by jameswex** [comment]
@gogasca What exact steps did you take to run into this error? Thanks.

**Comment by gogasca** [comment]
@jameswex I installed JupyterLab 1.2 and enabled wit-widget

```
jupyter labextension install wit-widget
jupyter lab build && \
jupyter lab clean && \
jlpm cache clean && \
npm cache clean --force
```
That automatically loaded the alpha version. 
Then In JupyterLab I clicked Terminal and I got the error above:

```
Launcher error
i is not a constructor
```

**Comment by jameswex** [comment]
Thanks. Do you have the same issue now if you install from fresh again, given that you won't get that alpha version now.

Also note that per https://github.com/pair-code/what-if-tool#how-do-i-enable-it-for-use-in-a-jupyterlab-or-cloud-ai-platform-notebook, you should also run "jupyter labextension install @jupyter-widgets/jupyterlab-manager" (and since you are jupyter lab 1.x, I think the command should technically be "jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0"

**Comment by gogasca** [comment]
All good now. I ended up pinning the 1.7.0 version. Thanks
