### ISSUE TITLE
Error when trying to reproduce example notebook locally

### ISSUE THREAD

**Issue by ricardobarroslourenco** [PAIR-code/what-if-tool#221]
I am trying to re-run locally the notebook provided in the tutorial section: https://colab.research.google.com/github/pair-code/what-if-tool/blob/master/WIT_Age_Regression.ipynb 

And I have got the following error:

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to create view for 'WITView' from module 'wit-widget' with model 'DOMWidgetModel' from module '@jupyter-widgets/base'
n@http://localhost:8888/static/lab/3790.af02260a4ebe28e0dd86.js?v=af02260a4ebe28e0dd86:1:49265
14416/create_view/e.state_change<@http://localhost:8888/static/lab/4416.9d6d0a2f3f9ed5d7b141.js?v=9d6d0a2f3f9ed5d7b141:1:4346

```
Any idea on what may be going on? I am using Jupyter-lab, and use the install procedures as described [here](https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/).

**Comment by jameswex** [comment]
what version of Jupyter Lab are you using? See https://github.com/pair-code/what-if-tool#how-do-i-enable-it-for-use-in-a-jupyterlab-or-cloud-ai-platform-notebook for some more details on using in Jupyter Lab.

**Comment by ricardobarroslourenco** [comment]
@jameswex , FYI, I have opened the same notebook, and it works smoothly on Colab (as expected).

Do you have any idea how can I make it work on my machine? I often use HPC premises to train my models, so I wonder if my environment setup may be causing issues.

**Comment by jameswex** [comment]
Hmm I also see issues running WIT in jupyterlab, testing from scratch today. I wonder if there's some regression due to some changes in jupyter deps or browsers.

In general, WIT isn't actively being developed.

I would recommend checking out our follow-on work LIT (https://pair-code.github.io/lit/) which works in JupyterLab, and Colab, and as a standalone server, and can do basically everything WIT can do and much, much more.

There will be a new release in ~2 weeks of LIT that adds a bunch of features and renames it to make it clear it isn't only for language models.

**Comment by ricardobarroslourenco** [comment]
I see. I will look forward into LIT then. Thanks for the follow-up.
