### ISSUE TITLE
Nothing shows up in my jupyter notebook

### ISSUE THREAD

**Issue by Bee-zest** [PAIR-code/what-if-tool#28]
I can successfully run the demo script ```COMPAS Recidivism Classifier ```in the jupyter notebook on my local machine. But nothing shows up at the end of jupyter notebook. I assume it will show up the visualization interface after I run ```WitWidget(config_builder, height=tool_height_in_px)```.

And I have installed  all the extension at the beginning of the jupyter notebook(python3).

```
! jupyter nbextension install --py --symlink --sys-prefix witwidget
! jupyter nbextension enable --py --sys-prefix witwidget
```

**Comment by jameswex** [comment]
Try running those commands on the command line in your environment before launching the jupyter notebook command instead of in the notebook to see if that changes the behavior. Thanks.

**Comment by Bee-zest** [comment]
> Try running those commands on the command line in your environment before launching the jupyter notebook command instead of in the notebook to see if that changes the behavior. Thanks.

That works! I have two additional quesitons.
1. I'm curious if it's possible to run whole thing in the jupyternotebook? 
2. Is it possible to change/add functionality to the template?

**Comment by jameswex** [comment]
Because of how ipywidgets work in jupyter, I couldn't find a way to install witwidget in a jupyter notebook and then view it in that same notebook, without at least refreshing the browser page after running the cell with the "!jupyter nbextension" commands.

But, if you use witwidget in colab notebooks, you can run the whole thing in one notebook as the colab version doesn't require those "jupyter nbextension" commands and so the widget can be fully loaded through just the "!pip install witwidget" and it will display without needing a page refresh or anything. Additionally, if you use Cloud AI Platform notebooks, witwidget comes pre-installed so you don't need to do anything except import the code and use it.

**Comment by jameswex** [comment]
Please re-open the issue if you have related questions.
