### ISSUE TITLE
Getting a full stacktrace for errors

### ISSUE THREAD

**Issue by zmjjmz** [PAIR-code/what-if-tool#61]
Hey there,

I've used the WIT in the past and am now coming back to it for a new project. I'm trying to use the Jupyter integrated widget with the inference done through a

- TF serving instance 
- In the `tensorflow/serving` docker container (2.1.0)
- Running a servable created from a Keras model
  - Using `tf.model.save`
- On another machine
- Talking via gRPC 

I'm getting a fairly unhelpful error whenever I try to run inference (when it starts up and when I click that Infer button):

```
TypeError('None has type NoneType, but expected one of: bytes, unicode',)
```

The configuration I've setup is as follows

```
wit_config = (
    witwidget.WitConfigBuilder(pred_df_ex)
    .set_inference_address('<host_redacted>:8500')
    .set_model_name('fts_test')
    .set_uses_predict_api(True)
    .set_predict_output_tensor('outputs')
    .set_model_type('classification')
    #.set_predict_input_tensor('inputs')
    .set_target_feature('label')
    .set_label_vocab(['No','Yes'])
)
```

I'm able to rule out that it's not getting a response from the server, since if I mess with the configuration to make it intentionally broken (e.g. if I uncomment that input tensor line) I'll get an error that probably could only come from the server.

```
<_Rendezvous of RPC that terminated with: status = StatusCode.INVALID_ARGUMENT details = "input size does not match signature: 1!=11 len({inputs}) != 
len({<feature_names_redacted>}). Sent extra: {inputs}. Missing but required: {<feature_names_redacted>}." debug_error_string = 
"{"created":"@1585001946.586897426","description":"Error received from peer ipv4:<ipaddr_redacted>:8500","file":"src/core/lib/surface
/call.cc","file_line":1052,"grpc_message":"input size does not match signature: 1!=11 
len({inputs}) != len({<feature_names_redacted>}). Sent extra: {inputs}. Missing but required: {<feature_names_redacted>}.","grpc_status":3}" >
```

I've verified that I can talk to the host no problem from this machine as well.

I'm not sure, honestly, whether or not that's an accurate assessment however -- what I'd need is the full stacktrace of that error. Any help would be appreciated.

**Comment by jameswex** [comment]
One way to possibly get a stack trace with the error is to create your WitWidget and save it to a var, like "ww = WitWidget(...)", and then in another cell call ww.infer(), which is what is called under the covers when inference needs to happen. The failure of that method call may give you a nice stack trace.

If not, you could pull down the repo and build the pip package locally, and make some code changes in the inference logic in your locally-built version to add some debugging prints and try to capture the error. Since your using TF serving, the code you would want to add debugging code to is at https://github.com/PAIR-code/what-if-tool/blob/master/utils/platform_utils.py#L160

**Comment by zmjjmz** [comment]
Thanks, I got a full stacktrace by calling `infer_impl`, which gives 

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-ad89c1a8d5fa> in <module>
----> 1 witwidgie.infer_impl()

~/proj/dataplayground3/lib/python3.5/site-packages/witwidget/notebook/base.py in infer_impl(self)
    178     (predictions, extra_output) = (
    179       inference_utils.run_inference_for_inference_results(
--> 180         examples_to_infer, serving_bundle))
    181     infer_objs.append(predictions)
    182     extra_output_objs.append(extra_output)

~/proj/dataplayground3/lib/python3.5/site-packages/witwidget/_utils/inference_utils.py in run_inference_for_inference_results(examples, serving_bundle)
    631   """Calls servo and wraps the inference results."""
    632   (inference_result_proto, extra_results) = run_inference(
--> 633     examples, serving_bundle)
    634   inferences = wrap_inference_results(inference_result_proto)
    635   infer_json = json_format.MessageToJson(

~/proj/dataplayground3/lib/python3.5/site-packages/witwidget/_utils/inference_utils.py in run_inference(examples, serving_bundle)
    860             extra_results)
    861   else:
--> 862     return (platform_utils.call_servo(examples, serving_bundle), None)

~/proj/dataplayground3/lib/python3.5/site-packages/witwidget/_utils/platform_utils.py in call_servo(examples, serving_bundle)
    190     # utility file is bundled in the witwidget pip package which has a dep
    191     # on TensorFlow.
--> 192     request.inputs[serving_bundle.predict_input_tensor].CopyFrom(
    193       tf.compat.v1.make_tensor_proto(
    194         values=[ex.SerializeToString() for ex in examples],

TypeError: None has type NoneType, but expected one of: bytes, unicode
```

I'll try and debug this more on my end, but if you have any insight in the meantime it'd be helpful.

**Comment by jameswex** [comment]
You do need to provide a predict_input_tensor setting to indicate what the name of the tensor that TF serving expect to extract the serialized tf.Example from.

How do you query your served model outside of WIT? What is the exact input format you send to the server and what is the serving signature of that served model?

If your model is served in a way that WIT doesn't currently support sending inputs to, another option is for you to use the set_custom_predict_fn option of WitConfigBuilder to write your own python function to take the tf.Example protos, send them to your model, and return back the results to WIT.

**Comment by zmjjmz** [comment]
I can't provide the actual feature names, but essentially it looks like this for the REST API

```
curl -d '
{"inputs":
    {
        "a":[11,2],
        "b":[1,2],
}}'   -X POST http://dat000:8501/v1/models/fts_test:predict

{
    "outputs": [
        [
            0.600828409,
            0.399171621
        ],
        [
            0.745381653,
            0.254618317
        ]
    ]
}
```

It's not clear to me what the `predict_input_tensor` setting should be here, and providing "inputs" gave me the error given above.

**Comment by jameswex** [comment]
Ah, I see, thanks. Since your model accepts feature dictionaries directly, and not a serialized tf.Example proto (as through the TF serving ClassificationRequest or PredictRequest APIs throgh the PredictionService (https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/prediction_service.proto#L15), the use of set_model_name and set_inference_address won't work for your case.

You can instead write your own python function that takes in a list of examples as input (which will be a list of items in pred_df_ex in your code sample), calls the model remotely, then returns the 2D list (outer list for each input that was predicted, inner list being length 2 containing probabilities for the negative and positive classes) that you see as the outputs value from your curl call. For some colab examples of custom predict functions (they don't call remote servers, so not an identical use-case), see https://colab.sandbox.google.com/github/PAIR-code/what-if-tool/blob/master/WIT_Smile_Detector.ipynb#scrollTo=E5fYynA9ZpPJ and https://colab.sandbox.google.com/github/pair-code/what-if-tool/blob/master/WIT_Toxicity_Text_Model_Comparison.ipynb

**Comment by jameswex** [comment]
Also we're working on improving our documentation, and will include questions like this is our upcoming FAQ. Sorry for the lack of clear documentation for use-cases such as yours.

**Comment by zmjjmz** [comment]
Ok, I was able to get this all working using a custom prediction function - thanks!
