### ISSUE TITLE
Can i use sklearn models directly without deploying them on AI platform.....please help.

### ISSUE THREAD

**Issue by Pem14604** [PAIR-code/what-if-tool#93]
![image](https://user-images.githubusercontent.com/43243814/83260894-268cf000-a1d8-11ea-9553-9b1962ec0a43.png)

Above code gives below error, seems like feature mismatch

![image](https://user-images.githubusercontent.com/43243814/83260998-4e7c5380-a1d8-11ea-9bb9-e8b83df77b09.png)

However if i use this model after deploying on AI platform then it works fine.
![image](https://user-images.githubusercontent.com/43243814/83261272-b29f1780-a1d8-11ea-929d-e0b09a1416ee.png)

**Comment by Pem14604** [comment]
Thanks james!!!

I dont' understand what is difference b/w model which is deployed on AI platform and which m using directly as both are having same data...this is related to my custom_predict_fn for sure as you have mentioned as well.  The thing is data which is being passed is not in shape as expected and also i don't know how to check the shape of the data which is going in adjustment function through config_builder.I tried to print "x" but it is givig list of values but don't have any ideas about cols.

just for your reference, below is the code, please help to resolve this.
https://github.com/Pem14604/whatiftool/blob/master/Whatif_xgboost.ipynb

I have tried many things like, please have a look.
**x_test[1:2].columns.tolist() and data.columns.tolist() have same cols.**

I dont know, what extaclty this line "**config_builder = (WitConfigBuilder(test_examples.tolist(), data.columns.tolist() + ["mortgage_status"])**" is doing....................seems like adding cols to my np array in which input feature and target variable stacked together using "**np.hstack((x_test[:num_wit_examples].values,y_test[:num_wit_examples].reshape(-1,1)))
test_examples**"

I am not getting from where it is taking "**f0,f1,f2..........cols**" during prediction actually i don't know how to check what is the shape of data which we are passing in custom_predict_fn.


just for your reference, below is the code, please help to resolve this.
https://github.com/Pem14604/whatiftool/blob/master/Whatif_xgboost.ipynb

![image](https://user-images.githubusercontent.com/43243814/83320271-75cc3280-a263-11ea-83ef-a04506b9eb13.png)

**Comment by jameswex** [comment]
Thanks for the notebook with the repro of the issue.

The config builder line you asked about is passing the examples to the What-If Tool as a 2D list of examples, where each row is a single example, as a list of feature values. The second argument is the list of names of the columns, which are the names of the input features (from data.columns), along with the name of the column we are trying to predict. That list of strings is provided in order to give the tool some feature names to display for the data being provided as flat lists. Alternatively, data can be provided to the tool as a list of json dictionaries (with keys as feature names and values as feature values), in which case that second argument of columns names wouldn't be necessary.

From playing with your notebook, it seems that the model is expecting a pandas data frame for the call to predict, and not just a simple 2D list of feature values for each datapoint. So, I adjusted your custom predict function to convert the data into a data frame (with the correct column  names) before passing it to the model. That got past the error. The second change I made was that .predict only returns the predicted class and not the raw class scores for both classes. So I changed it to use .predict_proba.

Here is the final, working function:

def adjust_prediction(x):
  x_df = pd.DataFrame(x, columns=data.columns.tolist())
  return bst.predict_proba(x_df)

Feel free to reopen this issue if you have more questions.

**Comment by Pem14604** [comment]
Thanks James...it is working fine!!!
