### ISSUE TITLE
Requirement: Multiclass classification data analysis using WIT...(Flower classification python file required)

### ISSUE THREAD

**Issue by Pem14604** [PAIR-code/what-if-tool#96]
Hi James/Team,
Can i have python file (.piynb) for Multiclass classification as m working on the same case.

Thanks in advance !!

**Comment by jameswex** [comment]
We don't have a multi-class notebook example currently, but it should look identical to our binary classification examples, except with a model that returns scores for more than just two classes (which is the binary classification case), and you call ".set_multi_class(True)" on WitConfigBuilder to indicate to the tool that it should be in multi-class mode, instead of binary classification mode.

**Comment by Pem14604** [comment]
Thanks James, it's done.....was unable to fine this parameter ".set_multi_class(True)".

![image](https://user-images.githubusercontent.com/43243814/84028657-bb4cd600-a9ae-11ea-816c-2774dbc82dc6.png)

**Comment by jameswex** [comment]
Glad you were able to get it to work. Sorry about the lack of documentation on that. We're building tutorials to cover every feature and will make sure to include this option in that documentation.
